[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[[language]]
name = "go"

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typescript"
# language-servers = [ { name = "typescript-language-server", except-features = ["format"] }, { name = "eslint", except-features = ["format"] } ]
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "\t" }
# formatter = { command = 'eslint_d', args = ["--stdin"] }

[[language]]
name = "tsx"
# language-servers = [ { name = "typescript-language-server", except-features = ["format"] }, { name = "eslint", except-features = ["format"] } ]
language-servers = [ "typescript-language-server" ]
indent = { tab-width = 4, unit = "\t" }
# formatter = { command = "eslint_d", args = ["--stdin", "--fix-to-stdout", "--stdin-filename", "file.tsx"] }
